#!/usr/bin/env python3
"""Turn downloaded OpenStreetMap tiles into compact Luau data modules.

Map data (c) OpenStreetMap contributors, Open Database License (ODbL):
https://www.openstreetmap.org/copyright

usage: python3 tools/osm_to_luau.py OSM_DIR [city ...]
  OSM_DIR is where tools/fetch_osm.py saved the tiles.
Writes src/shared/CityData/<Name>/*.luau.

Coordinates in the output are decimetres relative to the city centre,
x = east, z = south (so the map looks like a normal map from above).
"""
import math
import os
import random
import re
import sys
import zlib
from collections import defaultdict

import numpy as np
import shapely
from shapely.geometry import (GeometryCollection, LineString, MultiLineString,
                              MultiPolygon, Point, Polygon, box)
from shapely.geometry.polygon import orient
from shapely.ops import linemerge, polygonize, unary_union
from shapely.strtree import STRtree

sys.path.insert(0, os.path.dirname(__file__))
from osm_load import OSM  # noqa: E402
from cities import CITIES  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..")


# ---------------------------------------------------------------------------
# helpers
def num(v):
    """'12.5', '12 m', '40 ft', '3;4' -> metres (float) or None."""
    if v is None:
        return None
    v = v.split(";")[0].strip().replace(",", ".")
    m = re.match(r"^(-?\d+(?:\.\d+)?)\s*(m|ft|')?", v)
    if not m:
        return None
    x = float(m.group(1))
    if m.group(2) in ("ft", "'"):
        x *= 0.3048
    return x


def stable_rng(*keys):
    h = zlib.crc32(("|".join(str(k) for k in keys)).encode())
    return random.Random(h)


NAMED_COLOURS = {
    "white": 0xEEEAE2, "grey": 0x8D8D8D, "gray": 0x8D8D8D, "black": 0x2A2A2A,
    "brown": 0x6B4632, "red": 0x8E3B2E, "darkred": 0x6E2A22, "beige": 0xD9C9A8,
    "yellow": 0xE2C46A, "cream": 0xEDE3C8, "tan": 0xC8A77E, "orange": 0xC8763C,
    "pink": 0xD9A0A0, "blue": 0x4F6E95, "green": 0x4F7A55, "darkgray": 0x555555,
    "darkgrey": 0x555555, "lightgrey": 0xB8B8B8, "lightgray": 0xB8B8B8, "silver": 0xB9BDC2,
    "maroon": 0x6B2A2A, "sandybrown": 0xD8A060, "khaki": 0xC9BB8C, "ivory": 0xF2EEDD,
}


def colour(v):
    if not v:
        return None
    v = v.strip().lower()
    if re.match(r"^#[0-9a-f]{6}$", v):
        return int(v[1:], 16)
    if re.match(r"^#[0-9a-f]{3}$", v):
        return int("".join(c * 2 for c in v[1:]), 16)
    return NAMED_COLOURS.get(v.replace(" ", "").replace("_", ""))


def polys_of(g):
    if g is None or g.is_empty:
        return []
    if isinstance(g, Polygon):
        return [g]
    if isinstance(g, (MultiPolygon, GeometryCollection)):
        out = []
        for x in g.geoms:
            out += polys_of(x)
        return out
    return []


def lines_of(g):
    if g is None or g.is_empty:
        return []
    if isinstance(g, LineString):
        return [g]
    if isinstance(g, (MultiLineString, GeometryCollection)):
        out = []
        for x in g.geoms:
            out += lines_of(x)
        return out
    return []


class Writer:
    """Collects integer records and writes them as Luau string modules."""

    def __init__(self):
        self.lines = []

    def add(self, ints):
        self.lines.append(" ".join(v if isinstance(v, str) else str(int(round(v))) for v in ints))

    def modules(self, limit=150_000):
        chunks, cur, size = [], [], 0
        for line in self.lines:
            if size + len(line) > limit and cur:
                chunks.append("\n".join(cur))
                cur, size = [], 0
            cur.append(line)
            size += len(line) + 1
        if cur:
            chunks.append("\n".join(cur))
        return chunks


def luau_string_module(text, comment):
    return "-- " + comment + "\n-- Map data (c) OpenStreetMap contributors, ODbL. Generated by tools/osm_to_luau.py.\nreturn [==[\n" + text + "\n]==]\n"


# ---------------------------------------------------------------------------
class City:
    def __init__(self, key, cfg, osm_dir):
        self.key = key
        self.cfg = cfg
        self.o = OSM().load_dir(os.path.join(osm_dir, key))
        x0, y0, x1, y1 = cfg["bbox"]
        self.lat0 = (y0 + y1) / 2
        self.lon0 = (x0 + x1) / 2
        self.kx = math.cos(math.radians(self.lat0)) * 111320.0
        self.ky = 110540.0
        ax0, ay0 = self.ll(y0, x0)
        ax1, ay1 = self.ll(y1, x1)
        m = 12.0
        self.area = box(ax0 + m, ay0 + m, ax1 - m, ay1 - m)
        self.boundary = self.area.exterior
        self.stats = defaultdict(int)

    # lat/lon -> local metres (x east, y north)
    def ll(self, lat, lon):
        return ((lon - self.lon0) * self.kx, (lat - self.lat0) * self.ky)

    def node_xy(self, n):
        la, lo, _ = self.o.nodes[n]
        return self.ll(la, lo)

    def way_coords(self, wid):
        w = self.o.ways.get(wid)
        if not w:
            return None
        nds = w[0]
        if any(n not in self.o.nodes for n in nds):
            return None
        return [self.node_xy(n) for n in nds]

    @staticmethod
    def dm(v):
        return int(round(v * 10))

    def xz(self, x, y):
        """metres (x east, y north) -> (x, z) decimetres."""
        return self.dm(x), self.dm(-y)

    # -- polygons --------------------------------------------------------------
    def way_polygon(self, wid):
        c = self.way_coords(wid)
        if not c or len(c) < 4 or c[0] != c[-1]:
            return None
        p = Polygon(c)
        if not p.is_valid:
            p = p.buffer(0)
        return p if not p.is_empty else None

    def rel_polygon(self, rid, allow_open=False, inside_test=None):
        members, _ = self.o.rels[rid]
        outer, inner, missing = [], [], False
        for t, ref, role in members:
            if t != "way":
                continue
            c = self.way_coords(ref)
            if not c:
                missing = True
                continue
            (inner if role == "inner" else outer).append(LineString(c))
        if not outer:
            return None

        def rings(lines):
            if not lines:
                return [], []
            merged = linemerge(lines)
            parts = lines_of(merged)
            closed = [l for l in parts if l.is_ring and len(l.coords) >= 4]
            opened = [l for l in parts if not (l.is_ring and len(l.coords) >= 4)]
            return closed, opened

        oc, oo = rings(outer)
        ic, _ = rings(inner)
        polys = [Polygon(r).buffer(0) for r in oc]
        if oo and allow_open and inside_test is not None:
            # incomplete relation (cut by our download area): close it with
            # the area boundary and keep the faces that contain water lines
            faces = polygonize(unary_union(oo + [self.boundary]))
            for f in faces:
                if inside_test(f):
                    polys.append(f)
        if not polys:
            return None
        g = unary_union(polys)
        if ic:
            g = g.difference(unary_union([Polygon(r).buffer(0) for r in ic]))
        return g if not g.is_empty else None

    def area_features(self, match, allow_open=False, inside_test=None):
        """[(geometry, tags, osm id)] for closed ways and multipolygons."""
        out = []
        for wid, (nds, tags) in self.o.ways.items():
            if match(tags) and nds and nds[0] == nds[-1]:
                p = self.way_polygon(wid)
                if p is not None:
                    out.append((p, tags, wid))
        for rid, (members, tags) in self.o.rels.items():
            if tags.get("type") == "multipolygon" and match(tags):
                p = self.rel_polygon(rid, allow_open, inside_test)
                if p is not None:
                    out.append((p, tags, -rid))
        return out

    # ---------------------------------------------------------------------------
    def run(self):
        cfg = self.cfg
        self.collect_roads()
        self.collect_water()
        self.collect_buildings()
        self.collect_props()
        self.collect_lanes()
        self.pick_spots()
        self.write()

    # -- roads -------------------------------------------------------------------
    CAR = {"motorway": 14, "trunk": 14, "primary": 13, "secondary": 11, "tertiary": 9,
           "unclassified": 6.5, "residential": 6.5, "living_street": 5, "service": 4.5,
           "busway": 6, "primary_link": 7, "secondary_link": 7, "tertiary_link": 6,
           "motorway_link": 7, "trunk_link": 7, "road": 6}

    def road_kind(self, tags):
        hw = tags.get("highway")
        if not hw:
            return None
        if tags.get("tunnel") in ("yes", "building_passage", "culvert") or tags.get("location") == "underground":
            return None
        try:
            if int(tags.get("layer", "0").split(";")[0]) < 0:
                return None
        except ValueError:
            pass
        if tags.get("indoor") == "yes" or tags.get("area") == "yes":
            return None
        if hw in self.CAR:
            if hw == "service" and tags.get("service") in ("parking_aisle", "drive-through"):
                return None
            return "car"
        if hw == "cycleway":
            return "bike"
        if hw == "pedestrian":
            return "ped"
        if hw in ("footway", "path", "track", "bridleway"):
            if tags.get("footway") in ("sidewalk", "crossing", "traffic_island") and tags.get("bridge") != "yes":
                return "sidewalk"
            return "path"
        return None

    def road_width(self, kind, tags):
        w = num(tags.get("width"))
        hw = tags.get("highway")
        if kind == "car":
            lanes = num(tags.get("lanes"))
            base = self.CAR.get(hw, 6)
            if lanes and lanes >= 1:
                base = max(base * 0.6, min(lanes * 3.3, 36))
            if w and 3 <= w <= 40:
                base = w
            return base
        if kind == "bike":
            return w if w and 1.5 <= w <= 6 else 2.6
        if kind == "ped":
            return w if w and 2 <= w <= 30 else 7
        return w if w and 1 <= w <= 8 else 2.4

    SURF = {"asphalt": 0, "paving_stones": 1, "sett": 2, "cobblestone": 2, "unhewn_cobblestone": 2,
            "bricks": 1, "brick": 1, "concrete": 4, "concrete:plates": 4, "fine_gravel": 6, "gravel": 6,
            "compacted": 6, "dirt": 6, "ground": 6, "unpaved": 6, "sand": 6, "grass": 9, "wood": 7,
            "metal": 4, "paved": 0, "granite": 8, "stone": 2}

    def road_surface(self, kind, tags):
        s = tags.get("surface")
        code = self.SURF.get(s, None)
        style = self.cfg["style"]
        if code is None:
            if kind == "bike":
                code = 3 if style == "amsterdam" else 0
            elif kind == "ped":
                code = 5
            elif kind == "path":
                code = 6 if style == "paris" else 5
            else:
                code = 0
        if kind == "bike" and code == 0 and style == "amsterdam":
            code = 3  # Dutch bike paths are red asphalt
        if kind == "ped" and code == 1:
            code = 5
        if code == 1 and style != "amsterdam":
            code = 5
        return code

    def collect_roads(self):
        self.roads = []  # dict(kind, width, surf, flags, line (metres), tags, id)
        bridge_areas = [p for p, t, i in self.area_features(lambda t: t.get("man_made") == "bridge")]
        self.bridge_areas = [g for p in bridge_areas for g in polys_of(p.intersection(self.area))]
        bu = unary_union(self.bridge_areas) if self.bridge_areas else None
        for wid, (nds, tags) in self.o.ways.items():
            kind = self.road_kind(tags)
            if not kind:
                continue
            c = self.way_coords(wid)
            if not c or len(c) < 2:
                continue
            line = LineString(c)
            width = self.road_width(kind, tags)
            surf = self.road_surface(kind, tags)
            flags = 0
            is_bridge = tags.get("bridge") not in (None, "no")
            if is_bridge:
                flags |= 1
                if bu is not None and line.length > 0:
                    inside = line.intersection(bu).length / line.length
                    if inside > 0.6:
                        flags |= 8  # the bridge already has a deck polygon
            if tags.get("oneway") in ("yes", "1", "true"):
                flags |= 2
            if kind == "car" and (tags.get("cycleway") in ("lane", "track") or tags.get("cycleway:both") == "lane"
                                  or tags.get("cycleway:right") == "lane" or tags.get("cycleway:left") == "lane"):
                flags |= 32
            hw = tags.get("highway")
            if kind == "car" and hw in ("primary", "secondary", "tertiary", "trunk") and (num(tags.get("lanes")) or 2) >= 2:
                flags |= 64
            for part in lines_of(line.intersection(self.area)):
                part = part.simplify(0.3)
                if part.length < 1:
                    continue
                self.roads.append(dict(kind=kind, width=width, surf=surf, flags=flags, line=part, tags=tags, id=wid))
        self.stats["roads"] = len(self.roads)
        # tram rails
        self.trams = []
        for wid, (nds, tags) in self.o.ways.items():
            if tags.get("railway") == "tram" and tags.get("tunnel") != "yes":
                c = self.way_coords(wid)
                if c and len(c) >= 2:
                    for part in lines_of(LineString(c).intersection(self.area)):
                        if part.length > 2:
                            self.trams.append(dict(line=part.simplify(0.2), bridge=tags.get("bridge") not in (None, "no")))
        # index for "is this near a street?"
        street_lines = [r["line"] for r in self.roads if r["kind"] in ("car", "bike", "ped", "path")]
        self.street_tree = STRtree(street_lines) if street_lines else None
        self.car_roads = [r for r in self.roads if r["kind"] == "car"]
        self.car_tree = STRtree([r["line"] for r in self.car_roads]) if self.car_roads else None

    # -- water, grass, bridges, piers -------------------------------------------------
    def collect_water(self):
        cfg = self.cfg
        lines = []
        for wid, (nds, tags) in self.o.ways.items():
            if tags.get("waterway") in ("river", "canal"):
                c = self.way_coords(wid)
                if c and len(c) >= 2:
                    lines.append(LineString(c))
        river_lines = unary_union(lines) if lines else None

        def has_river(face):
            return river_lines is not None and face.intersects(river_lines) and face.area > 200

        feats = self.area_features(lambda t: (t.get("natural") == "water" or t.get("waterway") in ("riverbank", "dock")
                                              or t.get("landuse") in ("basin", "reservoir")) and t.get("tunnel") != "yes"
                                   and t.get("covered") != "yes", allow_open=True, inside_test=has_river)
        water = unary_union([f[0] for f in feats]) if feats else None
        self.water = [p for p in polys_of(water.intersection(self.area).buffer(0))] if water else []
        self.water = [p.simplify(0.4) for p in self.water if p.area > 8]
        self.water_union = unary_union(self.water) if self.water else None
        self.stats["water polys"] = len(self.water)
        self.river_lines = lines

        def is_green(t):
            return (t.get("leisure") in ("park", "garden", "playground", "dog_park", "common")
                    or t.get("landuse") in ("grass", "village_green", "meadow", "forest", "flowerbed", "recreation_ground", "cemetery")
                    or t.get("natural") in ("grassland", "scrub", "wood", "heath"))
        green = []
        for g, t, i in self.area_features(is_green):
            kind = 3 if (t.get("landuse") == "forest" or t.get("natural") in ("wood", "scrub")) else 2
            if t.get("leisure") == "playground":
                kind = 4
            if t.get("landuse") == "flowerbed":
                kind = 5
            for p in polys_of(g.intersection(self.area).buffer(0)):
                p = p.simplify(0.5)
                if p.area > 15:
                    if self.water_union is not None:
                        p2 = p.difference(self.water_union)
                        for q in polys_of(p2):
                            if q.area > 15:
                                green.append((kind, q))
                    else:
                        green.append((kind, p))
        # big parks are listed first so small flowerbeds paint on top
        green.sort(key=lambda kp: -kp[1].area)
        self.green = green
        self.stats["green polys"] = len(green)
        piers = []
        for g, t, i in self.area_features(lambda t: t.get("man_made") == "pier"):
            for p in polys_of(g.intersection(self.area)):
                if p.area > 4:
                    piers.append(p.simplify(0.3))
        self.piers = piers
        # pedestrian squares (Dam, Times Square...) are drawn as paving
        squares = []
        for g, t, i in self.area_features(lambda t: (t.get("highway") == "pedestrian" and t.get("area") == "yes")
                                          or t.get("area:highway") in ("pedestrian", "footway")
                                          or t.get("place") == "square"):
            for p in polys_of(g.intersection(self.area).buffer(0)):
                if p.area > 30:
                    squares.append(p.simplify(0.4))
        self.squares = squares

    # -- buildings ------------------------------------------------------------------------
    def collect_buildings(self):
        cfg = self.cfg
        style = cfg["style"]
        excl = [(Point(*self.ll(la, lo)), r) for (la, lo, r) in cfg.get("exclude", [])]

        def excluded(p):
            c = p.representative_point()
            return any(c.distance(pt) < r for pt, r in excl)

        def skip(t):
            b = t.get("building") or t.get("building:part")
            return (b in ("no", "construction", "ruins", "collapsed", "demolished", "proposed")
                    or t.get("location") == "underground" or t.get("layer", "0").startswith("-"))

        outlines = [f for f in self.area_features(lambda t: "building" in t and not skip(t)) if not excluded(f[0])]
        parts = [f for f in self.area_features(lambda t: "building:part" in t and "building" not in t and not skip(t)
                                                and t.get("building:part") not in ("no",)) if not excluded(f[0])]
        level_h = cfg["level_h"]

        def heights(t, parent=None):
            h = num(t.get("height"))
            levels = num(t.get("building:levels"))
            roof_levels = num(t.get("roof:levels")) or 0
            if h is None and levels is not None:
                h = levels * level_h + roof_levels * 2.6 + cfg.get("roof_extra", 0)
            if h is None and parent is not None:
                h = parent[0]
            if h is None:
                b = t.get("building", "yes")
                if b == "houseboat":
                    h = 3.2
                elif b in ("roof", "carport"):
                    h = 4
                elif b in ("shed", "garage", "kiosk", "hut", "cabin"):
                    h = 3.5
                else:
                    h = cfg["default_h"]
            mh = num(t.get("min_height"))
            if mh is None:
                ml = num(t.get("building:min_level"))
                mh = ml * level_h if ml else 0.0
            if t.get("building") in ("roof", "carport") and mh == 0:
                mh = max(0, h - 1.0)
            h = max(h, mh + 1.0)
            return min(h, 600), max(0, mh)

        out_geoms = [g for g, t, i in outlines]
        tree = STRtree(out_geoms) if out_geoms else None
        part_of = defaultdict(list)
        for k, (g, t, i) in enumerate(parts):
            if tree is None:
                continue
            idx = tree.query(g.representative_point(), predicate="intersects")
            if len(idx):
                part_of[int(idx[0])].append(k)
        solids = []  # (geom, h, mh, tags, id, kind)
        for k, (g, t, i) in enumerate(outlines):
            h, mh = heights(t)
            ps = part_of.get(k, [])
            if ps:
                cover = unary_union([parts[j][0] for j in ps]).area
                if cover >= 0.5 * g.area:
                    for j in ps:
                        pg, pt, pid = parts[j]
                        merged = dict(t)
                        merged.update(pt)
                        ph, pmh = heights(pt, (h, mh))
                        solids.append((pg, ph, pmh, merged, pid, "part"))
                    continue
            solids.append((g, h, mh, t, i, "building"))
        # parts with no outline at all
        claimed = {j for v in part_of.values() for j in v}
        for j, (g, t, i) in enumerate(parts):
            if j not in claimed and num(t.get("height")):
                h, mh = heights(t)
                solids.append((g, h, mh, t, i, "part"))
        # clip, simplify, orient
        final = []
        for g, h, mh, t, i, kind in solids:
            for p in polys_of(g.intersection(self.area)):
                p = p.simplify(0.35, preserve_topology=True)
                p = p.buffer(0) if not p.is_valid else p
                for q in polys_of(p):
                    if q.area < 5:
                        continue
                    # courtyards can't be seen from the street: fill them in
                    q = orient(Polygon(q.exterior), 1.0)
                    final.append(dict(geom=q, h=h, mh=mh, tags=t, id=i, kind=kind))
        # buildings deep inside a block can't be seen from the street: skip them
        open_geoms = [r["line"] for r in self.roads] + [w.exterior for w in self.water] + list(self.squares)
        if open_geoms and final:
            otree = STRtree(open_geoms)
            pi, gi = otree.query([b["geom"] for b in final], predicate="dwithin", distance=10.0)
            near = set(int(a) for a in pi)
            keep = []
            for i, b in enumerate(final):
                if i in near or b["h"] > 30:
                    keep.append(b)
            self.stats["hidden buildings skipped"] = len(final) - len(keep)
            final = keep
        # irregular footprints need triangles: simplify them a bit more
        for b in final:
            g = b["geom"]
            if len(g.exterior.coords) > 7 and solid_rects(g) is None:
                g2 = g.simplify(self.cfg.get("rough_simplify", 0.6), preserve_topology=True)
                if g2.is_valid and not g2.is_empty and isinstance(g2, Polygon) and g2.area > 0.9 * g.area:
                    b["geom"] = orient(g2, 1.0)
        self.buildings = final
        self.stats["buildings"] = len(final)
        self.classify_edges()

    def classify_edges(self):
        cfg = self.cfg
        bl = self.buildings
        tree = STRtree([b["geom"] for b in bl])
        shops = []
        for n, (la, lo, t) in self.o.nodes.items():
            if "shop" in t or t.get("amenity") in ("cafe", "restaurant", "fast_food", "ice_cream", "bar", "pub", "bank", "pharmacy"):
                shops.append(Point(*self.ll(la, lo)))
        shop_tree = STRtree(shops) if shops else None
        open_roads = [r for r in self.roads if r["kind"] in ("car", "bike", "ped", "path", "sidewalk")]
        open_tree_geoms = [r["line"] for r in open_roads]
        open_half = [r["width"] / 2 for r in open_roads]
        if self.water_union is not None:
            open_tree_geoms += [w.exterior for w in self.water]
            open_half += [0.0] * len(self.water)
        open_tree_geoms += [s for s in self.squares]
        open_half += [0.0] * len(self.squares)
        open_tree = STRtree(open_tree_geoms) if open_tree_geoms else None
        # gather every edge
        edges = []  # (building index, ring index, vertex index, mid, normal, length)
        for bi, b in enumerate(bl):
            rings = [list(b["geom"].exterior.coords)[:-1]] + [list(r.coords)[:-1] for r in b["geom"].interiors]
            b["rings"] = rings
            b["flags"] = [[0] * len(r) for r in rings]
            for ri, ring in enumerate(rings):
                n = len(ring)
                for vi in range(n):
                    a = ring[vi]
                    c = ring[(vi + 1) % n]
                    dx, dy = c[0] - a[0], c[1] - a[1]
                    L = math.hypot(dx, dy)
                    if L < 0.3:
                        continue
                    nx, ny = dy / L, -dx / L
                    edges.append((bi, ri, vi, ((a[0] + c[0]) / 2, (a[1] + c[1]) / 2), (nx, ny), L))
        if not edges:
            return
        mids = np.array([e[3] for e in edges])
        nrm = np.array([e[4] for e in edges])
        q1 = shapely.points(mids + nrm * 0.6)
        q2 = shapely.points(mids + nrm * 4.0)
        cover = defaultdict(list)
        pi, gi = tree.query(q1, predicate="intersects")
        for a, b in zip(pi, gi):
            cover[int(a)].append(int(b))
        near2 = set()
        pi, gi = tree.query(q2, predicate="intersects")
        for a, b in zip(pi, gi):
            if bl[int(b)]["h"] > 3:
                near2.add(int(a))
        street = set()
        if open_tree is not None:
            pts = shapely.points(mids)
            (pi, gi), dist = open_tree.query_nearest(pts, max_distance=60.0, return_distance=True)
            # a facade faces the street when the street edge is close by
            street = set(int(a) for a, g, d in zip(pi, gi, dist) if d - open_half[int(g)] <= 13.0)
        shopfront = set()
        if shop_tree is not None:
            pts = shapely.points(mids)
            pi, gi = shop_tree.query_nearest(pts, max_distance=7.0, return_distance=False)
            shopfront = set(int(a) for a in pi)
        counts = defaultdict(int)
        for k, (bi, ri, vi, mid, n, L) in enumerate(edges):
            b = bl[bi]
            flag = 1
            top = -1
            for oj in cover.get(k, []):
                if oj == bi:
                    continue
                o = bl[oj]
                if o["mh"] <= b["mh"] + 1.0:
                    top = max(top, o["h"])
            if top >= b["h"] - 0.8:
                flag = 0
            elif top < 0 and k not in near2 and k in street and ri == 0:
                flag = 3 if (k in shopfront and b["mh"] < 1) else 2
            b["flags"][ri][vi] = flag
            counts[flag] += 1
        self.stats["edges hidden/blank/street/shop"] = "%d/%d/%d/%d" % (counts[0], counts[1], counts[2], counts[3])

    # -- props ------------------------------------------------------------------------------
    def nearest_road_dir(self, x, y, kinds=("car",)):
        """direction (radians, math coords) and distance of the nearest road line."""
        tree, roads = self.car_tree, self.car_roads
        if tree is None:
            return 0.0, 1e9, None
        p = Point(x, y)
        idx = tree.query_nearest(p)
        if not len(idx):
            return 0.0, 1e9, None
        r = roads[int(idx[0])]
        line = r["line"]
        s = line.project(p)
        a = line.interpolate(max(0, s - 1))
        b = line.interpolate(min(line.length, s + 1))
        return math.atan2(b.y - a.y, b.x - a.x), line.distance(p), r

    def collect_props(self):
        cfg = self.cfg
        props = []  # (type, x, y, angle radians math, extra)
        inside = self.area.contains
        rng = stable_rng(self.key, "props")
        lamp_light = 0
        for n, (la, lo, t) in self.o.nodes.items():
            x, y = self.ll(la, lo)
            if not inside(Point(x, y)):
                continue
            if t.get("natural") == "tree":
                hgt = num(t.get("height"))
                props.append((1, x, y, 0, int((hgt or 0) * 10)))
            elif t.get("highway") == "street_lamp":
                lamp_light += 1
                props.append((2, x, y, 0, 1 if lamp_light % cfg.get("light_every", 2) == 0 else 0))
            elif t.get("amenity") == "bench":
                ang, d, _ = self.nearest_road_dir(x, y)
                props.append((3, x, y, ang, 0))
            elif t.get("amenity") == "bicycle_parking":
                ang, d, _ = self.nearest_road_dir(x, y)
                cap = int(num(t.get("capacity")) or 4)
                props.append((4, x, y, ang, max(2, min(cap, 6))))
            elif t.get("barrier") == "bollard":
                props.append((5, x, y, 0, 0))
            elif t.get("amenity") == "fountain":
                props.append((6, x, y, 0, 0))
            elif t.get("highway") == "traffic_signals":
                ang, d, r = self.nearest_road_dir(x, y)
                if r is not None and d < 12:
                    props.append((7, x, y, ang, int(r["width"] * 10)))
            elif t.get("advertising") == "column":
                props.append((8, x, y, 0, 0))
            elif t.get("emergency") == "fire_hydrant":
                props.append((9, x, y, 0, 0))
            elif t.get("highway") == "bus_stop" and t.get("shelter") == "yes":
                ang, d, _ = self.nearest_road_dir(x, y)
                props.append((10, x, y, ang, 0))
            elif t.get("highway") == "crossing" and (t.get("crossing") in ("zebra", "marked", "uncontrolled", "traffic_signals")
                                                     or t.get("crossing:markings") in ("yes", "zebra", "ladder", "lines")):
                ang, d, r = self.nearest_road_dir(x, y)
                if r is not None and d < 3 and r["tags"].get("highway") not in ("service",):
                    props.append((11, x, y, ang, int(r["width"] * 10)))
        # thin out the very dense layers (keeps the city smooth on phones)
        caps = cfg.get("prop_caps", {})
        by_type = defaultdict(list)
        for p in props:
            by_type[p[0]].append(p)
        final = []
        for ty, lst in by_type.items():
            cap = caps.get(ty)
            if cap and len(lst) > cap:
                rng.shuffle(lst)
                lst = lst[:cap]
            final += lst
        self.props = final
        cnt = defaultdict(int)
        for p in final:
            cnt[p[0]] += 1
        self.stats["props"] = dict(cnt)

    # -- traffic lanes ------------------------------------------------------------------------
    def collect_lanes(self):
        lanes = []  # (kind, width, flags, j0, j1, line, y)
        junction = {}

        def jid(pt):
            key = (round(pt[0] / 1.5), round(pt[1] / 1.5))
            if key not in junction:
                junction[key] = len(junction) + 1
            return junction[key]

        style = self.cfg["style"]
        for r in self.roads:
            k = r["kind"]
            hw = r["tags"].get("highway")
            kinds = []
            if k == "car" and hw not in ("service",):
                kinds.append("car")
                if style == "amsterdam" or r["flags"] & 32 or hw in ("residential", "living_street", "unclassified", "tertiary"):
                    kinds.append("bike")
            elif k == "bike":
                kinds.append("bike")
            elif k in ("ped", "path", "sidewalk"):
                kinds.append("walk")
                if k == "ped" and style == "amsterdam":
                    kinds.append("bike")
            for kind in kinds:
                line = r["line"]
                if line.length < 8:
                    continue
                c = list(line.coords)
                lanes.append((kind, r["width"], r["flags"] & 3, jid(c[0]), jid(c[-1]), line, 0.35 if r["flags"] & 1 else 0))
        for t in self.trams:
            line = t["line"]
            c = list(line.coords)
            if line.length > 30:
                lanes.append(("tram", 3, 0, jid(c[0]), jid(c[-1]), line, 0))
        if self.water_union is not None:
            for l in self.river_lines:
                for part in lines_of(l.intersection(self.water_union.buffer(-4))):
                    part = part.simplify(1)
                    if part.length > 60:
                        c = list(part.coords)
                        lanes.append(("boat", 6, 0, jid(c[0]), jid(c[-1]), part, -99))
        self.lanes = lanes
        cnt = defaultdict(int)
        for l in lanes:
            cnt[l[0]] += 1
        self.stats["lanes"] = dict(cnt)

    # -- coins, doors, shops, landmarks ---------------------------------------------------------
    def pick_spots(self):
        cfg = self.cfg
        rng = stable_rng(self.key, "spots")
        # coins along streets you can ride on
        cands = [r for r in self.roads if r["kind"] in ("car", "bike", "ped") and r["tags"].get("highway") != "service"]
        coins = []
        for r in cands:
            L = r["line"].length
            s = rng.uniform(5, 30)
            while s < L - 5:
                if rng.random() < cfg.get("coin_density", 0.08):
                    p = r["line"].interpolate(s)
                    coins.append((p.x, p.y, 0.35 if r["flags"] & 1 else 0))
                s += 30
        rng.shuffle(coins)
        self.coins = self.spread(coins, 25, cfg.get("coins", 260))
        # delivery doors on street facades
        doors = []
        for b in self.buildings:
            if b["mh"] > 0.5 or b["tags"].get("building") in ("houseboat", "roof"):
                continue
            ring = b["rings"][0]
            for vi, f in enumerate(b["flags"][0]):
                if f == 2:
                    a, c = ring[vi], ring[(vi + 1) % len(ring)]
                    dx, dy = c[0] - a[0], c[1] - a[1]
                    L = math.hypot(dx, dy)
                    if L > 3:
                        nx, ny = dy / L, -dx / L
                        doors.append(((a[0] + c[0]) / 2 + nx * 1.8, (a[1] + c[1]) / 2 + ny * 1.8, 0))
        rng.shuffle(doors)
        if self.water_union is not None:
            doors = [d for d in doors if not self.water_union.contains(Point(d[0], d[1]))]
        self.doors = self.spread(doors, 45, 320)
        # shops for delivery jobs (kid friendly ones only)
        shops = []
        for n, (la, lo, t) in self.o.nodes.items():
            label = shop_label(t, cfg["style"])
            if not label:
                continue
            x, y = self.ll(la, lo)
            if not self.area.buffer(-40).contains(Point(x, y)):
                continue
            ang, d, r = self.nearest_road_dir(x, y)
            if r is None or d > 40:
                continue
            # stand in front of the shop, on the street side
            line = r["line"]
            p = line.interpolate(line.project(Point(x, y)))
            vx, vy = x - p.x, y - p.y
            L = math.hypot(vx, vy) or 1
            off = min(d, r["width"] / 2 + 1.5)
            shops.append((p.x + vx / L * off, p.y + vy / L * off, 0, label))
        rng.shuffle(shops)
        self.shops = self.spread(shops, cfg.get("shop_spacing", 180), cfg.get("shops", 14))
        # landmarks
        self.landmarks = []
        for lm in cfg["landmarks"]:
            x, y = self.ll(lm["lat"], lm["lon"])
            self.landmarks.append(dict(lm, x=x, y=y))
        la, lo, la2, lo2 = cfg["spawn"]
        x, y = self.ll(la, lo)
        x2, y2 = self.ll(la2, lo2)
        self.spawn = (x, y, game_yaw(math.atan2(y2 - y, x2 - x)))

    @staticmethod
    def spread(items, min_dist, limit):
        out = []
        for it in items:
            if all(math.hypot(it[0] - o[0], it[1] - o[1]) >= min_dist for o in out):
                out.append(it)
                if len(out) >= limit:
                    break
        return out

    # -- building styles ------------------------------------------------------------------------
    def building_style(self, b, rng):
        """-> (style, wall colour, material code, roof colour, facade edge)."""
        cfg = self.cfg
        t = b["tags"]
        h, mh = b["h"], b["mh"]
        kind = t.get("building") or t.get("building:part") or "yes"
        geom = b["geom"]
        mrr = geom.minimum_rotated_rectangle
        cs = list(mrr.exterior.coords)
        w1, w2 = math.dist(cs[0], cs[1]), math.dist(cs[1], cs[2])
        narrow = min(w1, w2)
        flags = b["flags"][0]
        ring = b["rings"][0]
        street_edges = [vi for vi, f in enumerate(flags) if f >= 2]
        facade = -1
        if street_edges:
            # the shortest street edge longer than 2.5 m is the front
            best = None
            for vi in street_edges:
                a, c = ring[vi], ring[(vi + 1) % len(ring)]
                L = math.dist(a, c)
                if L >= 2.5 and (best is None or L < best[0]):
                    best = (L, vi)
            if best:
                facade = best[1]
        pal = cfg["palette"]
        wall, mat = weighted(rng, pal["walls"])
        roof = rng.choice(pal["roofs"])
        tc = colour(t.get("building:colour"))
        if tc is not None:
            wall = tc
        rc = colour(t.get("roof:colour"))
        if rc is not None:
            roof = rc
        material = t.get("building:material") or t.get("building:facade:material")
        mat_codes = {"brick": 0, "plaster": 1, "stone": 2, "limestone": 2, "sandstone": 5, "concrete": 3,
                     "glass": 4, "wood": 6, "marble": 7, "granite": 7, "metal": 8, "steel": 8}
        if material in mat_codes:
            mat = mat_codes[material]
        style = 0
        s = cfg["style"]
        if kind == "houseboat":
            style = 6
            wall, mat = rng.choice(pal["boats"]), 6
        elif kind in ("church", "cathedral", "chapel") or t.get("amenity") == "place_of_worship":
            style = 7
            wall, mat = pal["church"]
        elif kind in ("roof", "carport"):
            style = 9
        elif s == "amsterdam":
            if 6 <= h <= 32 and narrow <= 13 and facade >= 0 and mh < 1 and kind not in ("industrial", "train_station", "transportation", "office") and t.get("roof:shape") != "flat":
                style = 1
        elif s == "paris":
            if h >= 11 and mh < 1 and kind not in ("industrial", "train_station", "transportation", "school", "sports_centre", "stadium", "garage", "service"):
                style = 2
        elif s == "newyork":
            if material == "glass" or (h > 120 and rng.random() < 0.55):
                style, mat = 4, 4
                wall = rng.choice(pal["glass"])
            elif h > 40:
                style = 5
                if material not in mat_codes:
                    wall, mat = weighted(rng, pal["towers"])
            else:
                style = 3
        return style, wall, mat, roof, facade

    # -- output ------------------------------------------------------------------------------------
    def encode_solid(self, head, geom, rings, flags, facade, geo):
        """One building record: head + outline + the shapes that fill it.

        head = [style, top dm, base dm, wall colour, material, roof colour]
        then: n_outer n_total facade FLAGS mode x0 z0 (dx dz)... geometry
        FLAGS is one digit per edge. mode 1: n rects (cx cz w d yaw_mrad)...
        mode 0: triangle vertex indices.
        """
        verts, fl = [], []
        for ri, ring in enumerate(rings):
            for vi, pt in enumerate(ring):
                verts.append(pt)
                fl.append(flags[ri][vi])
        mode = 1  # 1: boxes, 2: boxes whose +Z side is a street front, 0: triangles
        rects = solid_rects(geom)
        if rects is None and facade >= 0 and not is_corner(rings[0], flags[0], facade):
            rects = facade_box(geom, rings[0], facade)
            mode = 2
        if rects is None and facade >= 0:
            rects = multi_facade_boxes(geom, rings[0], flags[0])
            mode = 2
            if rects is not None:
                geo["corner box buildings"] += 1
        if rects is None and not geom.interiors and len(rings[0]) <= 6:
            cx, cy, w, d, th = mrr_params(geom)
            mode = 1
            if w * d <= geom.area * 1.12:
                rects = [(cx, cy, w, d, th)]
        if rects is None:
            mode = 0
        tri_idx = []
        if rects is None:
            index = {(round(x, 4), round(y, 4)): i for i, (x, y) in enumerate(verts)}
            try:
                tris = shapely.constrained_delaunay_triangles(geom)
            except Exception:
                tris = shapely.delaunay_triangles(geom)
            for t in polys_of(tris):
                cs = list(t.exterior.coords)[:3]
                ids = [index.get((round(x, 4), round(y, 4))) for x, y in cs]
                if None in ids or not geom.buffer(0.01).contains(t.representative_point()):
                    continue
                tri_idx += ids
            if not tri_idx:
                return None
            geo["wedges"] += 2 * len(tri_idx) // 3
            geo["tri buildings"] += 1
        else:
            geo["boxes"] += len(rects)
            geo["box buildings"] += 1
        rec = list(head) + [len(rings[0]), len(verts), facade, "".join(str(min(9, f)) for f in fl)]
        rec.append(mode)
        px, pz = None, None
        for (x, y) in verts:
            X, Z = self.xz(x, y)
            if px is None:
                rec += [X, Z]
            else:
                rec += [X - px, Z - pz]
            px, pz = X, Z
        if rects is None:
            rec += tri_idx
        else:
            rec.append(len(rects))
            for cx, cy, w, d, th in rects:
                X, Z = self.xz(cx, cy)
                rec += [X, Z, self.dm(w), self.dm(d), int(round(th * 1000))]
        return rec

    def write(self):
        cfg = self.cfg
        out_dir = os.path.join(ROOT, "src", "shared", "CityData", cfg["module"])
        os.makedirs(out_dir, exist_ok=True)
        for f in os.listdir(out_dir):
            if f.endswith(".luau"):
                os.remove(os.path.join(out_dir, f))
        xz = self.xz
        # buildings
        bw = Writer()
        styles = defaultdict(int)
        win_estimate = 0
        mansards = 0
        geo = defaultdict(int)
        for b in self.buildings:
            rng = stable_rng(self.key, b["id"], round(b["geom"].area))
            style, wall, mat, roof, facade = self.building_style(b, rng)
            styles[style] += 1
            geom = b["geom"]
            h, mh = b["h"], b["mh"]
            if style == 2 and not num(b["tags"].get("roof:levels")):
                h += 3.4  # Paris: the zinc mansard storey on top
            rec = self.encode_solid([style, self.dm(h), self.dm(mh), wall, mat, roof], geom, b["rings"], b["flags"], facade, geo)
            if rec is None:
                continue
            bw.add(rec)
            ring = b["rings"][0]
            for vi, f in enumerate(b["flags"][0]):
                if f >= 2:
                    L = math.dist(ring[vi], ring[(vi + 1) % len(ring)])
                    win_estimate += int(L / 3.2) * max(1, int((h - mh) / cfg["level_h"]))
        self.stats["geometry"] = dict(geo)
        self.stats["building styles"] = dict(styles)
        self.stats["windows (est.)"] = win_estimate
        self.stats["mansards"] = mansards
        chunks = bw.modules()
        for i, text in enumerate(chunks):
            with open(os.path.join(out_dir, "Buildings%d.luau" % (i + 1)), "w") as f:
                f.write(luau_string_module(text, "Buildings of %s (part %d)" % (cfg["module"], i + 1)))
        self.stats["building modules"] = len(chunks)
        # roads: kind width surface flags n points...
        kinds = {"car": 1, "bike": 2, "ped": 3, "path": 4, "sidewalk": 5}
        rw = Writer()
        for r in self.roads:
            if r["kind"] == "sidewalk" and not (r["flags"] & 1):
                continue  # pavements are the ground itself
            c = list(r["line"].coords)
            rec = [kinds[r["kind"]], self.dm(r["width"]), r["surf"], r["flags"], len(c)]
            x0, z0 = xz(*c[0])
            for i, (x, y) in enumerate(c):
                X, Z = xz(x, y)
                rec += [X, Z] if i == 0 else [X - x0, Z - z0]
            rw.add(rec)
        for t in self.trams:
            c = list(t["line"].coords)
            rec = [6, 14, 0, 1 if t["bridge"] else 0, len(c)]
            x0, z0 = xz(*c[0])
            for i, (x, y) in enumerate(c):
                X, Z = xz(x, y)
                rec += [X, Z] if i == 0 else [X - x0, Z - z0]
            rw.add(rec)
        for i, text in enumerate(rw.modules()):
            with open(os.path.join(out_dir, "Roads%d.luau" % (i + 1)), "w") as f:
                f.write(luau_string_module(text, "Streets of %s (part %d)" % (cfg["module"], i + 1)))
        # areas: kind nrings len... points (kind 1 water, 2 grass, 3 forest, 4 playground, 5 flowers,
        # 6 bridge deck, 7 pier, 8 square)
        aw = Writer()

        def add_area(kind, p, flag_fn=None):
            rings = [list(p.exterior.coords)[:-1]] + [list(r.coords)[:-1] for r in p.interiors]
            rings = [r for r in rings if len(r) >= 3]
            if not rings:
                return
            rec = [kind, len(rings)] + [len(r) for r in rings]
            x0, z0 = xz(*rings[0][0])
            first = True
            for ring in rings:
                for vi, (x, y) in enumerate(ring):
                    X, Z = xz(x, y)
                    fl = flag_fn(ring, vi) if flag_fn else 0
                    if first:
                        rec += [X, Z, fl]
                        first = False
                    else:
                        rec += [X - x0, Z - z0, fl]
            aw.add(rec)

        bnd = self.area.exterior

        def quay_flag(ring, vi):
            a, c = ring[vi], ring[(vi + 1) % len(ring)]
            mid = Point((a[0] + c[0]) / 2, (a[1] + c[1]) / 2)
            return 0 if bnd.distance(mid) < 0.5 else 1

        for p in self.water:
            add_area(1, orient(p, 1.0), quay_flag)
        for kind, p in self.green:
            add_area(kind, orient(p, 1.0))
        wu = self.water_union

        def parapet_flag(ring, vi):
            if wu is None:
                return 0
            a, c = ring[vi], ring[(vi + 1) % len(ring)]
            dx, dy = c[0] - a[0], c[1] - a[1]
            L = math.hypot(dx, dy) or 1
            mid = ((a[0] + c[0]) / 2 + dy / L * 1.0, (a[1] + c[1]) / 2 - dx / L * 1.0)
            return 1 if wu.contains(Point(mid)) else 0

        for p in self.bridge_areas:
            for q in polys_of(p.simplify(0.3)):
                add_area(6, orient(q, 1.0), parapet_flag)
        for p in self.piers:
            add_area(7, orient(p, 1.0))
        for p in self.squares:
            add_area(8, orient(p, 1.0))
        for i, text in enumerate(aw.modules()):
            with open(os.path.join(out_dir, "Areas%d.luau" % (i + 1)), "w") as f:
                f.write(luau_string_module(text, "Water, parks and bridges of %s (part %d)" % (cfg["module"], i + 1)))
        # props: type x z angle(millirad, game yaw) extra
        pw = Writer()
        for ty, x, y, ang, extra in self.props:
            X, Z = xz(x, y)
            pw.add([ty, X, Z, int(round(game_yaw(ang) * 1000)), extra])
        for i, text in enumerate(pw.modules()):
            with open(os.path.join(out_dir, "Props%d.luau" % (i + 1)), "w") as f:
                f.write(luau_string_module(text, "Trees, lamps and street furniture of %s (part %d)" % (cfg["module"], i + 1)))
        # lanes: kind width flags j0 j1 y n points
        lane_codes = {"car": 1, "bike": 2, "walk": 3, "boat": 4, "tram": 5}
        lw = Writer()
        for kind, width, flags, j0, j1, line, y in self.lanes:
            c = list(line.coords)
            rec = [lane_codes[kind], self.dm(width), flags, j0, j1, self.dm(y) if y > -90 else -999, len(c)]
            x0, z0 = xz(*c[0])
            for i, (x, yy) in enumerate(c):
                X, Z = xz(x, yy)
                rec += [X, Z] if i == 0 else [X - x0, Z - z0]
            lw.add(rec)
        for i, text in enumerate(lw.modules()):
            with open(os.path.join(out_dir, "Lanes%d.luau" % (i + 1)), "w") as f:
                f.write(luau_string_module(text, "Traffic lanes of %s (part %d)" % (cfg["module"], i + 1)))
        # meta
        self.write_meta(out_dir)

    def write_meta(self, out_dir):
        cfg = self.cfg
        xz = self.xz
        x0, y0 = self.area.bounds[0], self.area.bounds[1]
        x1, y1 = self.area.bounds[2], self.area.bounds[3]
        L = []
        L.append("--!strict")
        L.append("-- %s: settings and points of interest. Generated by tools/osm_to_luau.py." % cfg["module"])
        L.append("-- Map data (c) OpenStreetMap contributors, ODbL.")
        L.append("return {")
        L.append('\tname = "%s",' % cfg["module"])
        L.append('\tstyle = "%s",' % cfg["style"])
        L.append("\t-- playable area in decimetres (x east, z south)")
        L.append("\tbounds = { %d, %d, %d, %d }," % (self.dm(x0), self.dm(-y1), self.dm(x1), self.dm(-y0)))
        L.append("\twaterLevel = %d, -- studs" % cfg["water_level_studs"])
        L.append("\tlevelHeight = %d, -- decimetres" % self.dm(cfg["level_h"]))
        sx, sz = xz(self.spawn[0], self.spawn[1])
        L.append("\tspawn = { x = %d, z = %d, yaw = %.3f }," % (sx, sz, self.spawn[2]))
        L.append("\tlandmarks = {")
        for lm in self.landmarks:
            X, Z = xz(lm["x"], lm["y"])
            L.append('\t\t{ id = "%s", name = "%s", x = %d, z = %d, radius = %d, fact = "%s" },' % (
                lm["id"], lm["name"], X, Z, self.dm(lm["radius"]), lm["fact"].replace('"', '\\"')))
        L.append("\t},")
        L.append("\t-- hand-made landmark models: position, turn and size (decimetres)")
        L.append("\tmodels = {")
        for md in cfg.get("models", []):
            x, y = self.ll(md["lat"], md["lon"])
            yaw, w, d = 0.0, 0.0, 0.0
            if md.get("way"):
                g = self.way_polygon(md["way"])
                if g is not None:
                    cx, cy, w, d, th = mrr_params(g)
                    if d > w:
                        w, d, th = d, w, th + math.pi / 2
                    yaw = th
            if md.get("face"):
                fx, fy = self.ll(*md["face"])
                yaw = game_yaw(math.atan2(fy - y, fx - x))
            X, Z = xz(x, y)
            L.append('\t\t{ kind = "%s", x = %d, z = %d, yaw = %.4f, w = %d, d = %d },' % (md["kind"], X, Z, yaw, self.dm(w), self.dm(d)))
        L.append("\t},")
        L.append("\tshops = {")
        for x, y, h, label in self.shops:
            X, Z = xz(x, y)
            L.append('\t\t{ x = %d, z = %d, label = "%s" },' % (X, Z, label))
        L.append("\t},")
        L.append("\tcoins = {")
        for i in range(0, len(self.coins), 8):
            L.append("\t\t" + " ".join("%d, %d, %d," % (xz(c[0], c[1]) + (self.dm(c[2]),)) for c in self.coins[i:i + 8]))
        L.append("\t},")
        L.append("\tdoors = {")
        for i in range(0, len(self.doors), 8):
            L.append("\t\t" + " ".join("%d, %d," % xz(d[0], d[1]) for d in self.doors[i:i + 8]))
        L.append("\t},")
        L.append("}")
        with open(os.path.join(out_dir, "Meta.luau"), "w") as f:
            f.write("\n".join(L) + "\n")
        # index module listing the data parts
        names = sorted(f[:-5] for f in os.listdir(out_dir) if f.endswith(".luau") and f not in ("Meta.luau", "init.luau"))
        groups = defaultdict(list)
        for n in names:
            groups[re.sub(r"\d+$", "", n)].append(n)
        I = ["--!strict", "-- Lists the data modules of %s. Generated by tools/osm_to_luau.py." % cfg["module"], "", "return {"]
        I.append("\tmeta = require(script.Meta),")
        for g in ("Buildings", "Roads", "Areas", "Props", "Lanes"):
            parts = sorted(groups.get(g, []), key=lambda s: int(re.sub(r"\D", "", s) or 0))
            I.append("\t%s = { %s }," % (g.lower(), ", ".join("script.%s" % p for p in parts)))
        I.append("}")
        with open(os.path.join(out_dir, "init.luau"), "w") as f:
            f.write("\n".join(I) + "\n")


def mrr_params(poly):
    mrr = poly.minimum_rotated_rectangle
    cs = list(mrr.exterior.coords)[:4]
    e1 = (cs[1][0] - cs[0][0], cs[1][1] - cs[0][1])
    e2 = (cs[2][0] - cs[1][0], cs[2][1] - cs[1][1])
    c = mrr.centroid
    return (c.x, c.y, math.hypot(*e1), math.hypot(*e2), math.atan2(e1[1], e1[0]))


def is_corner(ring, flags, facade):
    """Does the building also face a street at an angle (a corner house)?"""
    n = len(ring)
    a, c = ring[facade], ring[(facade + 1) % n]
    fa = math.atan2(c[1] - a[1], c[0] - a[0])
    for vi, f in enumerate(flags):
        if f >= 2 and vi != facade:
            p, q = ring[vi], ring[(vi + 1) % n]
            if math.dist(p, q) < 2.5:
                continue
            d = abs((math.atan2(q[1] - p[1], q[0] - p[0]) - fa + math.pi) % (2 * math.pi) - math.pi)
            if d > math.radians(12):
                return True
    return False


def multi_facade_boxes(poly, ring, flags):
    """Corner houses: one box behind each street front (fronts that line up
    are joined). Boxes may not stick out of the footprint."""
    n = len(ring)
    spans = []  # (start vertex, end vertex)
    for vi in range(n):
        if flags[vi] < 2:
            continue
        a, c = ring[vi], ring[(vi + 1) % n]
        if spans and spans[-1][1] == vi:
            s0 = ring[spans[-1][0]]
            d1 = math.atan2(c[1] - a[1], c[0] - a[0])
            d0 = math.atan2(a[1] - s0[1], a[0] - s0[0])
            if abs((d1 - d0 + math.pi) % (2 * math.pi) - math.pi) < math.radians(8):
                spans[-1] = (spans[-1][0], (vi + 1) % n)
                continue
        spans.append((vi, (vi + 1) % n))
    spans = [sp for sp in spans if math.dist(ring[sp[0]], ring[sp[1]]) >= 2.5]
    if not spans or len(spans) > 5:
        return None
    fence = poly.buffer(0.6, join_style="mitre")
    out, shapes = [], []
    for i0, i1 in spans:
        a, c = ring[i0], ring[i1]
        L = math.dist(a, c)
        ux, uy = (c[0] - a[0]) / L, (c[1] - a[1]) / L
        ix, iy = -uy, ux
        dmax = max((p[0] - a[0]) * ix + (p[1] - a[1]) * iy for p in ring)
        placed = False
        for depth in (dmax, dmax * 0.75, dmax * 0.55, dmax * 0.4, 9.0, 6.0, 4.0):
            if depth < 2.5 or depth > dmax + 0.01:
                continue
            quad = Polygon([a, c, (c[0] + ix * depth, c[1] + iy * depth), (a[0] + ix * depth, a[1] + iy * depth)])
            if fence.contains(quad):
                out.append((a[0] + ux * L / 2 + ix * depth / 2, a[1] + uy * L / 2 + iy * depth / 2, L, depth, math.atan2(uy, ux)))
                shapes.append(quad)
                placed = True
                break
        if not placed:
            return None
    if unary_union(shapes).area < 0.6 * poly.area:
        return None
    return out


def facade_box(poly, ring, vi):
    """A box lined up with the street front, as deep as the building.
    The front is exact; small differences hide at the back."""
    n = len(ring)
    a, c = ring[vi], ring[(vi + 1) % n]
    L = math.dist(a, c)
    if L < 2:
        return None
    ux, uy = (c[0] - a[0]) / L, (c[1] - a[1]) / L
    ix, iy = -uy, ux  # inward normal (rings are counter-clockwise)
    ss, ts = [], []
    for p in ring:
        dx, dy = p[0] - a[0], p[1] - a[1]
        ss.append(dx * ux + dy * uy)
        ts.append(dx * ix + dy * iy)
    depth = max(ts)
    if depth < 2 or depth > 70 or min(ts) < -0.6:
        return None
    if L * depth > 2.2 * poly.area or L * depth < 0.6 * poly.area:
        return None
    cx = a[0] + ux * L / 2 + ix * depth / 2
    cy = a[1] + uy * L / 2 + iy * depth / 2
    return [(cx, cy, L, depth, math.atan2(uy, ux))]


def solid_rects(poly):
    """Boxes that fill the footprint, or None if triangles are better."""
    cx, cy, w, d, th = mrr_params(poly)
    if not poly.interiors and w * d <= poly.area * 1.05:
        return [(cx, cy, w, d, th)]
    rects = ortho_rects(poly)
    if rects is None:
        return None
    n_verts = len(poly.exterior.coords) - 1 + sum(len(r.coords) - 1 for r in poly.interiors)
    wedges = 2 * (n_verts - 2 + 2 * len(poly.interiors))
    return rects if len(rects) <= max(2, wedges) else None


def ortho_rects(poly, tol=math.radians(5)):
    """Split an (almost) right-angled footprint into boxes."""
    ring = list(poly.exterior.coords)
    best, ang = 0, 0
    for a, b in zip(ring, ring[1:]):
        L = math.dist(a, b)
        if L > best:
            best, ang = L, math.atan2(b[1] - a[1], b[0] - a[0])
    for r in [poly.exterior] + list(poly.interiors):
        cs = list(r.coords)
        for a, b in zip(cs, cs[1:]):
            if math.dist(a, b) < 0.8:
                continue
            t = (math.atan2(b[1] - a[1], b[0] - a[0]) - ang) % (math.pi / 2)
            if min(t, math.pi / 2 - t) > tol:
                return None
    from shapely import affinity
    rp = affinity.rotate(poly, -ang, origin=(0, 0), use_radians=True)
    minx, miny, maxx, maxy = rp.bounds
    xs = sorted(set(round(x, 1) for r in [rp.exterior] + list(rp.interiors) for x, _ in r.coords))
    clean = []
    for x in xs:
        if not clean or x - clean[-1] > 0.25:
            clean.append(x)
    clean[0], clean[-1] = minx, maxx
    rects, openr = [], {}
    for i in range(len(clean) - 1):
        x0, x1 = clean[i], clean[i + 1]
        if x1 - x0 < 0.05:
            continue
        strip = rp.intersection(box(x0, miny - 1, x1, maxy + 1))
        ivs = set()
        for q in polys_of(strip):
            if q.area > 0.05:
                b = q.bounds
                ivs.add((round(b[1] * 4) / 4, round(b[3] * 4) / 4))
        nxt = {}
        for iv in ivs:
            if iv in openr:
                nxt[iv] = [openr[iv][0], x1]
            else:
                nxt[iv] = [x0, x1]
        for iv, span in openr.items():
            if iv not in nxt:
                rects.append((span, iv))
        openr = nxt
    for iv, span in openr.items():
        rects.append((span, iv))
    out = []
    c, s = math.cos(ang), math.sin(ang)
    for (x0, x1), (y0, y1) in rects:
        mx, my = (x0 + x1) / 2, (y0 + y1) / 2
        out.append((mx * c - my * s, mx * s + my * c, x1 - x0, y1 - y0, ang))
    return out


def weighted(rng, items):
    total = sum(w for w, *_ in items)
    r = rng.random() * total
    for w, col, mat in items:
        r -= w
        if r <= 0:
            return col, mat
    return items[-1][1], items[-1][2]


def is_rect(ring):
    if len(ring) != 4:
        return False
    for i in range(4):
        a, b, c = ring[i - 1], ring[i], ring[(i + 1) % 4]
        v1 = (a[0] - b[0], a[1] - b[1])
        v2 = (c[0] - b[0], c[1] - b[1])
        l1, l2 = math.hypot(*v1), math.hypot(*v2)
        if l1 < 0.5 or l2 < 0.5:
            return False
        if abs((v1[0] * v2[0] + v1[1] * v2[1]) / (l1 * l2)) > 0.035:
            return False
    return True


def game_yaw(math_angle):
    """Direction in map maths (x east, y north) -> Roblox yaw where a part's
    local -Z (its front) points along the direction."""
    dx, dy = math.cos(math_angle), math.sin(math_angle)
    # world x = dx, world z = -dy; front -Z = (-sin yaw, -cos yaw)
    return math.atan2(-dx, dy)


FOOD = {
    "bakery": "Bakery", "pastry": "Bakery", "ice_cream": "Ice Cream", "confectionery": "Sweet Shop",
    "chocolate": "Chocolate Shop", "cheese": "Cheese Shop", "deli": "Deli",
}


def shop_label(t, style):
    if t.get("shop") in FOOD:
        return FOOD[t["shop"]]
    a = t.get("amenity")
    if a == "ice_cream":
        return "Ice Cream"
    cuisine = (t.get("cuisine") or "").split(";")[0]
    if a == "fast_food":
        return {"pizza": "Pizza Place", "bagel": "Bagel Shop", "hot_dog": "Hot Dog Stand", "burger": "Burger Bar",
                "crepe": "Crêperie", "pancake": "Pancake House", "dutch": "Pancake House", "friture": "Fries",
                "french_fries": "Fries", "sandwich": "Sandwich Shop", "donut": "Donut Shop"}.get(cuisine)
    if a == "cafe" and style in ("paris", "newyork") and t.get("name"):
        return "Café"
    if a == "restaurant" and cuisine in ("pancake", "crepe", "pizza"):
        return {"pancake": "Pancake House", "crepe": "Crêperie", "pizza": "Pizza Place"}[cuisine]
    return None


def main():
    osm_dir = sys.argv[1]
    keys = sys.argv[2:] or list(CITIES)
    for key in keys:
        c = City(key, CITIES[key], osm_dir)
        c.run()
        print("==", key)
        for k, v in c.stats.items():
            print("   %-32s %s" % (k, v))


if __name__ == "__main__":
    main()
